export const ROUTES = {
  CATALOGUE_SCREEN: 'CatalogueScreen',
  COFFEE_VIEW_SCREEN: 'CoffeeViewScreen',
  CART_SCREEN: 'CartScreen',
  CATALOGUE_STACK: 'CatalogueStack',
  CART_STACK: 'CartStack',
  PROFILE_STACK: 'ProfileStack',
  FAVOURITES_STACK: 'FavouritesStack',
  SETTINGS_SCREEN: 'SettingsScreen',
  FAVOURITES_SCREEN: 'FavouritesScreen',
  REGISTER_USER_SCREEN: 'RegisterUserScreen',
  LOGIN_SCREEN: 'LoginScreen',
  AUTH_STACK: 'AUTH_STACK',
  APP_VIEW: 'APP_VIEW',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
};
