import {StyleSheet} from 'react-native';
import {APP_BACKGROUND_COLOR, FONTS} from '../../core/constants';

export const styles = StyleSheet.create({
  catalogueScreenContainer: {
    flex: 1,
    backgroundColor: APP_BACKGROUND_COLOR,
  },
  catalogueScreenHeader: {
    height: 120,
    width: '100%',
    flexDirection: 'row',
    paddingHorizontal: '5%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  catalogueLogoStyle: {
    height: 120,
    width: 120,
  },
  catalogueAvatarContainer: {
    height: 60,
    width: 60,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#f4ce9a',
  },
  searchBarContainer: {
    height: 40,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 15,
    width: '90%',
    paddingHorizontal: '5%',
    alignSelf: 'center',
    backgroundColor: '#171017',
  },
  searchBarInput: {
    height: '100%',
    width: '80%',
    color: '#EFE3C8',
    fontFamily: FONTS.ROSARIVO_REGULAR,
    marginLeft: 10,
    fontSize: 12,
  },
  rotateText: {
    color: '#EFE3C8',
    fontSize: 12,
    fontFamily: FONTS.ROSARIVO_REGULAR,
    marginBottom: -4,
    transform: [{rotate: '-90deg'}],
  },
  catalogueContainer: {flex: 1, flexDirection: 'row'},
  catalogueCategoriesContainer: {
    backgroundColor: '#38232a',
    flex: 1,
    borderTopRightRadius: 25,
  },
  catalogueScrollViewContainer: {paddingVertical: 20},
  catalogueItemsContainer: {width: '90%', paddingHorizontal: 5},
  catalogueItemsWrapperFlex: {flex: 1},
  catalogueItemsFlatListContainer: {paddingBottom: 25, flexGrow: 1},
  catalogueItemsFlatListColumnWrapper: {justifyContent: 'space-around'},
  catalogueItem: {
    width: '45%',
    height: 250,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginVertical: 5,
    padding: 10,
    justifyContent: 'space-between',
  },
  catalogueItemImage: {
    width: '100%',
    height: '65%',
    borderRadius: 10,
    marginBottom: 5,
  },
  catalogueItemTxt: {
    fontFamily: FONTS.ROSARIVO_REGULAR,
    color: 'white',
    fontSize: 12,
    textAlign: 'center',
  },
  catalogueItemQtySelector: {
    width: '100%',
    height: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  catalogueItemPriceContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  catalogueItemPriceTxt: {
    fontFamily: FONTS.ROSARIVO_REGULAR,
    color: 'white',
    fontSize: 14,
  },
  catalogueItemAddBtn: {
    height: '100%',
    width: '35%',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#EFE3C8',
  },
});
